# Generated by Django 5.2.6 on 2025-09-18 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField()),
                ('car_model', models.CharField(max_length=100)),
                ('car_number', models.IntegerField()),
                ('fuel_type', models.CharField()),
                ('fc', models.IntegerField()),
            ],
        ),
    ]
